apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traininghub-ingress
  namespace: traininghub
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
  - host: traininghub.local
    http:
      paths:
      - path: /api/v1/users
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 5001
      - path: /api/v1/courses
        pathType: Prefix
        backend:
          service:
            name: course-service
            port:
              number: 5002
      - path: /api/v1/certificates
        pathType: Prefix
        backend:
          service:
            name: certificate-service
            port:
              number: 5004
