apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traininghub

resources:
  - frontend.yaml
  - ai-ops-service.yaml
  - namespace.yaml
  - app-config.yaml
  - mysql.yaml
  - user-service.yaml
  - course-service.yaml
  - certificate-service.yaml
  - user-service-hpa.yaml
  - course-service-hpa.yaml
  - certificate-service-hpa.yaml
  - frontend-service-hpa.yaml
  - network-policies.yaml
  - ingress.yaml

configMapGenerator:
  - name: mysql-initdb
    files:
      - init.sql=init.sql

generatorOptions:
  disableNameSuffixHash: true
