apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: traininghub
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-controller
  namespace: traininghub
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - frontend-service
          - user-service
          - course-service
          - certificate-service
          - ai-ops-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 5001
        - protocol: TCP
          port: 5002
        - protocol: TCP
          port: 5004
        - protocol: TCP
          port: 5005
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-apis
  namespace: traininghub
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - user-service
          - course-service
          - certificate-service
          - ai-ops-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend-service
      ports:
        - protocol: TCP
          port: 5001
        - protocol: TCP
          port: 5002
        - protocol: TCP
          port: 5004
        - protocol: TCP
          port: 5005
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-services-to-mysql
  namespace: traininghub
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - user-service
                  - course-service
                  - certificate-service
      ports:
        - protocol: TCP
          port: 3306
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-monitoring-scrapes
  namespace: traininghub
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - frontend-service
          - user-service
          - course-service
          - certificate-service
          - ai-ops-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 5001
        - protocol: TCP
          port: 5002
        - protocol: TCP
          port: 5004
        - protocol: TCP
          port: 5005
