apiVersion: v1
kind: Secret
metadata:
  name: traininghub-secrets
  namespace: traininghub
type: Opaque
stringData:
  SECRET_KEY: CHANGE_ME
  JWT_SECRET_KEY: CHANGE_ME
  MYSQL_ROOT_PASSWORD: CHANGE_ME
  MYSQL_PASSWORD: CHANGE_ME
  DEFAULT_ADMIN_PASSWORD: CHANGE_ME
  AIOPS_WEBHOOK_TOKEN: CHANGE_ME
